version: '3'

services:
  app:
    image: 'tasker:latest'
    build:
      context: .
    #container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app_db
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    ports:
      - '8080:8080'
          
  db:
    image: 'postgres:15.3'
    #container_name: db
    environment:
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - '5432:5432'